-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table public."Session"
--     RENAME column date to start_at;
--
-- alter table public."Session"
--     add column end_at timestamptz;
