-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."User"
(
    user_id SERIAL,
    email character varying(50) NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    "User_Has_Role" integer NOT NULL,
    "User_Presents_Session_FK" integer,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."Session"
(
    session_id SERIAL,
    name character varying(50) NOT NULL,
    date date NOT NULL,
    "time" time with time zone NOT NULL,
    summarization character varying(500)[] NOT NULL,
    "Session_PresentedBy_User" integer NOT NULL,
    PRIMARY KEY (session_id)
);

CREATE TABLE public."SessionUpload"
(
    session_upload_id SERIAL,
    url character varying(200) NOT NULL,
    "Upload_For_Session_FK" integer NOT NULL,
    "Upload_IsOf_UploadType_FK" integer NOT NULL,
    PRIMARY KEY (session_upload_id)
);

CREATE TABLE public."UserUpload"
(
    user_upload_id SERIAL,
    url character varying(200) NOT NULL,
    "Upload_For_User_FK" integer NOT NULL,
    "Upload_IsOf_UploadType_FK" integer,
    PRIMARY KEY (user_upload_id)
);

CREATE TABLE public."Role"
(
    role_id SERIAL,
    name character varying(20) NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE public."UploadType"
(
    upload_type_id SERIAL,
    name character varying(20),
    PRIMARY KEY (upload_type_id)
);

ALTER TABLE public."User"
    ADD FOREIGN KEY ("User_Has_Role")
    REFERENCES public."Role" (role_id)
    NOT VALID;


ALTER TABLE public."UserUpload"
    ADD FOREIGN KEY ("Upload_For_User_FK")
    REFERENCES public."User" (user_id)
    NOT VALID;


ALTER TABLE public."SessionUpload"
    ADD FOREIGN KEY ("Upload_For_Session_FK")
    REFERENCES public."Session" (session_id)
    NOT VALID;


ALTER TABLE public."Session"
    ADD FOREIGN KEY ("Session_PresentedBy_User")
    REFERENCES public."User" (user_id)
    NOT VALID;


ALTER TABLE public."UserUpload"
    ADD FOREIGN KEY ("Upload_IsOf_UploadType_FK")
    REFERENCES public."UploadType" (upload_type_id)
    NOT VALID;


ALTER TABLE public."SessionUpload"
    ADD FOREIGN KEY ("Upload_IsOf_UploadType_FK")
    REFERENCES public."UploadType" (upload_type_id)
    NOT VALID;

END;
