-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table public."Session"
--    alter column date type timestamptz using (date + time)::timestamptz;
